export const HANDLE_INPUT = "HANDLE_INPUT";
export const LOGIN_SUCCESS = "LOGIN_SUCCESS";
export const LOGIN_FAILURE = "LOGIN_FAILURE";
export const CLEAR_CREDENTIALS = "CLEAR_CREDENTIALS";
export const FETCH_POSTS_SUCCESS = "FETCH_POSTS_SUCCESS";
export const FETCH_POSTS_FAILURE = "FETCH_POSTS_FAILURE";
export const SET_SUBMITTING = "SET_SUBMITTING";
